### ISSUE TITLE
Virtual Console Box Art And E-Shop Box Art Resolution Confusion

### ISSUE THREAD

**Issue by Distantworld101** [citra-emu/citra-games-wiki#185]
In The Contributing guide It Says 
and  i Quote

> The required process for getting Virtual console Boxart is: Downsize it to approximately 328x300

But If you go-to the Add A Game Section it says

> If this is a eShop title, the game's homescreen should be used instead. In this case, the image should be a compressed .png of 500x300.

There is nothing about Virtual Console Box Art

**Comment by TheKoopaKingdom** [comment]
What exactly are you confused about? eShop and Virtual Console are two different things, our eShop boxart has the 3DS's top screen resolution 500x300, and our Virtual Console boxart has the resolution of what's being used, ~328x300 because something like a Game Boy VC doesn't take up all of the 3DS' screen.

**Comment by Leo626** [comment]
I think what OP is trying to say is that some users might classify virtual console games as eShop games since they are downloaded from the eShop. The PR builder doesn't mention virtual console games for boxart and so users might use the resolution for eShop games instead.

**Comment by j-selby** [comment]
Fixed with latest version of PR builder.
